# Generated by Django 4.2.4 on 2023-09-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_search_search_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('stream_video_url', models.CharField(max_length=255)),
                ('thumbnail_url', models.CharField(max_length=255)),
            ],
        ),
    ]
